version: '3'
services:
    flask_nginx_webserver:
        container_name: flask_nginx
        build:
            dockerfile: dockerfile
        tty: true
        stdin_open: true
        volumes:
            - ./app:/app
            # - ./app:/var/www/html/app
        # working_dir: /var/www/html/app
        ports:
            - '80:80'
        environment:
            - FLASK_APP=/var/www/html/app/main.py
            - FLASK_DEBUG=1
            - STATIC_URL=/static
            - STATIC_PATH=/var/www/html/app/static
