version: '3'
services:
    flask_nginx_webserver:
        container_name: flask_nginx
        restart: 'unless-stopped'
        build:
            context: ../
            dockerfile: ./docker/dockerfile
            args:
                APP_FOLDER: ${APP_FOLDER}
        # docker run -i
        tty: true
        # docker run -t
        stdin_open: true
        volumes:
            - ./../${APP_FOLDER}:${APP_FOLDER}
        ports:
            - ${LISTEN_PORT}:${LISTEN_PORT}
        env_file:
            - ./../env/docker.env
