version: '3'
services:
    flask_nginx_webserver:
        container_name: flask_nginx
        restart: 'unless-stopped'
        build:
            context: ./../
            dockerfile: ./docker/dockerfile
        tty: true
        stdin_open: true
        volumes:
            - ./../app:/app
            # - ./app:/var/www/html/app
        # working_dir: /var/www/html/app
        ports:
            - '80:80'
        env_file:
            - ../env/flask.env
